apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/backend
images:
- name: backend
  newName: REPLACE_WITH_ECR_URL
  newTag: latest
# UAT Specific configurations (e.g., more replicas)
patches:
- target:
    kind: Deployment
    name: backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
